# Generated by Django 4.2 on 2023-06-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('others_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('email_address', models.EmailField(max_length=254)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('courses', models.CharField(blank=True, max_length=100)),
                ('any_programming_skill', models.CharField(max_length=10)),
                ('choose_internship_type', models.CharField(max_length=100)),
                ('number_of_months', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('upload_photo', models.ImageField(upload_to='photos/')),
                ('upload_it_letter', models.FileField(upload_to='it_letters/')),
            ],
        ),
    ]
