# Generated by Django 4.2 on 2023-06-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_biodata_options_biodata_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodata',
            options={},
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='username',
        ),
        migrations.AlterField(
            model_name='biodata',
            name='courses',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='others_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='school_name',
            field=models.CharField(max_length=255),
        ),
    ]
