# Generated by Django 4.2 on 2023-06-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_biodata_options_remove_biodata_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='any_programming_skill',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='choose_internship_type',
            field=models.CharField(choices=[('secondary', 'Secondary Internship Programs'), ('undergraduate', 'Undergraduate Internship Programs'), ('postgraduate', 'Postgraduate Internship Programs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
