# Generated by Django 4.2 on 2023-06-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_biodata_any_programming_skill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodata',
            old_name='others_name',
            new_name='other_names',
        ),
    ]
