# Generated by Django 4.2 on 2023-06-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_biodata_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
